Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,27 +1,37 @@
 name: Deploy for preview
+
 on:
   push:
     paths:
-      - mailtest/test.txt
-    
+      - mailtest/test2.txt
+
 jobs:
- precheck:
+  precheck:
     runs-on: windows-latest
-    
+
     steps:
-      - uses: actions/checkout@v2.3.4
-
-      - name: Check if File Pushed.
+      - name: Check if File Exists
         run: |
-          echo "push Process success."  
-          
- upload:
-  needs: precheck
-  runs-on: windows-latest
+          file_path="mailtest/test2.txt"
+          if [ ! -f "$file_path" ]; then
+            echo "File not found, job should not start"
+            exit 1
+          fi
 
-  steps:
-    - name: job step.
-      run: |
+          last_modified=$(git log -1 --format=%ct -- "$file_path")
+          current_modified=$(git log -1 --format=%ct)
+          if [ "$last_modified" -eq "$current_modified" ]; then
+            echo "File exists but not modified, job should not start"
+            exit 1
+          fi
+
+  upload:
+    needs: precheck
+    runs-on: windows-latest
+
+    steps:
+      - name: Your job step
+        run: |
         
         
         
